internalUserRestEndpoint:
  handler: application/domain/users/controllers/userController.restHandler
  events:
  - http:
      path: /internal/user/{id}
      method: ANY
      cors: true
  - http:
      path: /internal/user
      method: ANY
      cors: true

queueListener:
  handler: application/command/sqsTrigger.handler
  timeout: 120
  events:
  - sqs:
      arn: !GetAtt SQSQueue.Arn

smokeTestCommand:
  handler: application/command/smokeTestCommand.handler
  timeout: 120

migrateCommand:
  handler: application/command/migrateCommand.handler
  timeout: 120

rdsEC2PauseSync:
  # dispatcher:
  handler: application/command/rdsEC2PauseSyncCommand.handler
  timeout: 12
  environment:
    BASTION_HOST_INSTANCE_ID: !Ref BastionHost
  events:
    - sns:
        arn: !Ref AuroraRDSSNSTopic
        topicName: AuroraRDSSNSTopic
