version: "3.5"

services:
  node:
    build: .
    working_dir: /var/task
    environment:
    - NODE_ENV=dev
    volumes:
    - ./:/var/task
    command: bash -c 'cd localPrerequisites && ./init.sh && tail -f /dev/null'
    depends_on:
    - mysql
    - dynamodb
    ports:
    - 3000:3000

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./data/mysql/:/var/lib/mysql
    ports:
    - 3306:3306

  dynamodb:
    image: amazon/dynamodb-local
    ports:
    - 8000:8000

  sqs:
    image: vsouza/sqs-local
    ports:
    - 9324:9324
